### ISSUE TITLE
How to create a brand new div every time the event is triggered

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/circle-maker#1]
Hi @thomasjbradley, 

Currently I can get one circle appear at random positions on page when a key is pressed down but am still trying to get my head around the following (probably fundamental programming concepts):

- How can I create a brand new div _every time_ the event is triggered? Foreach loop? I tried it (put it inside the event listener) but couldn't make it work;

- Markbot says all `var` declarations must be at top of the function scope but when I did that, I couldn't get the circle on the page;

- Markbot also expects to see `$('<div>')` where I did `$body.append('<div class="ball"></div>')`. Does that mean I need to add class separately with jQuery's addClass function?

Good project and I want to make sure I get these core concepts right.

Thanks!

**Comment by thomasjbradley** [comment]
> How can I create a brand new div every time the event is triggered? Foreach loop? I tried it (put it inside the event listener) but couldn't make it work;

Inside the event listener function, you need to create the `<div>` before appending it to the body:

```js
var $div = $("<div>");
```

Then you can append that div variable to the body, add a class to it and adjust its CSS.

> Markbot says all var declarations must be at top of the function scope but when I did that, I couldn't get the circle on the page;

Yes, all the vars should be at the top, here:
https://github.com/C-G-G/circle-maker/blob/gh-pages/js/main.js#L6

> Markbot also expects to see $('<div>') where I did $body.append('<div class="ball"></div>'). Does that mean I need to add class separately with jQuery's addClass function?

Solution to question 1 also solves this one.

**Comment by C-G-G** [comment]
I'm still doing something wrong but cannot figure out what. Markbot says the element, `.ball`, doesn't exist on the page. 

`var $div = $('<div>');`

  `$body.append($div).addClass('ball');`

  `$('.ball').css('left', randLeft);`
  `$('.ball').css('top', randTop);`

While here, may I also ask how come we don't close the div tag? 

Thanks @thomasjbradley

**Comment by thomasjbradley** [comment]
The `addClass` is operating on `body` because that’s the element that’s selected at the start of that line/chain, it needs to operate on the div. And the `.css` lines need to operate on the div too.

```js
$div.addClass()
$div.css()
```

> While here, may I also ask how come we don't close the div tag?

jQuery does that automatically for us.

**Comment by C-G-G** [comment]
Sorry for taking your time but this is still not working and Markbot is still giving the same error above. The circle appears on page when a key is pressed but only once:

`$body.append($div);`
`$div.addClass('ball');`

`$div.css('left', randLeft);`
`$div.css('top', randTop);`

@thomasjbradley

**Comment by thomasjbradley** [comment]
The two randomization lines need to be inside the keydown function so you get a new randomization each time.

It is working now. If you open the developer tools and inspect the circle you’ll see many divs being added to the same place.

**Comment by C-G-G** [comment]
Thanks @thomasjbradley ... yes, it works now but for some reason Markbot is still not happy. 

When I put the two randomization lines inside the keydown function, it says, they should be outside so instead of creating variables, I put the random function directly as parameter to css() function. Now it says the element, `.ball`, doesn't exist on the page although the circles appear on there:

<img width="1232" alt="Screen Shot 2022-01-29 at 2 39 08 PM" src="https://user-images.githubusercontent.com/16348315/151675183-a536921d-e209-4de8-8419-6de5ae0711cf.png">

**Comment by thomasjbradley** [comment]
It’s a small change, but kinda confusing.

This line here:
https://github.com/C-G-G/circle-maker/blob/gh-pages/js/main.js#L5

Is listening for a `keydown` on the `body`—but elements don’t receive key events unless they are focused. For this to work the `body` element needs to be focused first.

When listening for general `keydown` events, it’s best to always listen directly to the document, aka, `html`:

```js
$('html').on(…
```

**Comment by C-G-G** [comment]
Thanks a lot! I gave the optional challenge a shot too (making background-color randomized). I was able to form the solution (logic and structure) in my head but had to look it up the rest (probably the most critical/ essential part, lol). Well, regardless, I'm happy to have been able to make it work. 

@thomasjbradley
